# Generated by Django 5.2.2 on 2025-06-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_board_user_board_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
