# Generated by Django 5.2.2 on 2025-06-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_comment_edited_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AddField(
            model_name='board',
            name='member_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of member emails'),
        ),
    ]
